### ISSUE TITLE
package is too big, need to check data being included

### ISSUE THREAD

**Issue by ejardim** [flr/mse#13]

**Comment by iagomosqueira** [comment]
They do not seem that big

```
-rw-rw-r-- 1 mosqu003   42 Dec 11  2018 datalist
-rw-rw-r-- 1 mosqu003 2.6M Dec 11  2018 cod.RData
-rw-rw-r-- 1 mosqu003  896 Dec 11  2018 indicators.RData
-rw-rw-r-- 1 mosqu003 6.4M Nov 27 10:10 p4om.RData
```
But we only need to have 1 OM as example. Maybe we need at least 1 or 2 FLmse too. Let's make them short. I will try. Now, cod or ple4?

**Comment by ejardim** [comment]
Cod is not really public I think ... the package is more than 20 MB at the moment

**Comment by iagomosqueira** [comment]
There was an extra copy of p4om, so another 10Mb, in examples. Deleting it now

**Comment by iagomosqueira** [comment]
cod being deleted too

**Comment by iagomosqueira** [comment]
cod was a simulated one, not NS OM

**Comment by iagomosqueira** [comment]
Package is now down to 9Mb, of which 8.6 Mb com from the p4om FLom example dataset.

**Comment by ejardim** [comment]
Do we need to have that object in the package ?

**Comment by iagomosqueira** [comment]
We should have an example object to use in help examples. we could make it smaller, down to 150 iters?

**Comment by ejardim** [comment]
We're using 25 in the course and it worked fine ...

**Comment by iagomosqueira** [comment]
OK, will try with 50 maybe, otherwise quantiles look funny

**Comment by iagomosqueira** [comment]
> object.size(om)
2024848 bytes

With 50 iters. Is this OK?

**Comment by ejardim** [comment]
Ok to me.

**Comment by iagomosqueira** [comment]
Object and script changed in e6acd3293a74ff47154e94381c86068f63b4b4d6
