### ISSUE TITLE
How to cite flr/mse?

### ISSUE THREAD

**Issue by k-doering-NOAA** [flr/mse#30]
I went looking for the JOSS article listed in the [citation file](https://github.com/flr/mse/blob/c2cb8f86ed7a99e3ca3de81fa69bf24cdd63f19b/inst/CITATION), but couldn't find it on the JOSS website. Could the article be linked?

**Comment by iagomosqueira** [comment]
The CITATION file was pushed by mistake, this paper is still a work in progress. You could use the [initial project report](https://publications.jrc.ec.europa.eu/repository/handle/JRC106750). BibTeX for it is available [here](https://publications.jrc.ec.europa.eu/repository/bibtex/JRC106750).

**Comment by k-doering-NOAA** [comment]
Thanks so much, and thank you for including the bibtex for the initial project report!

**Comment by iagomosqueira** [comment]
Thanks for your interest. The BibTeX is nicely generated by the JRC publications database.
