### ISSUE TITLE
which master for latest installation?

### ISSUE THREAD

**Issue by mebrooks** [flr/mse#4]
Is the main master in repository "flr/mse" or "iagomosqueira/mse"?

The installation instructions say
```
library(devtools) install_github("iagomosqueira/mse")
```

**Comment by mebrooks** [comment]
Also, there should be a semicolon in
```
library(devtools); install_github("flr/mse")
```

**Comment by iagomosqueira** [comment]
Thanks, tyypos noiw corrected. Master is now here, in flr/mse
