### ISSUE TITLE
mse install on R 3.6.1 on Ubuntu 18.04

### ISSUE THREAD

**Issue by ldbk** [flr/mse#9]
Hello,

When trying to install mse from github, I've got this error message :

Error: package or namespace load failed for ‘ggplotFL’:
 (converted from warning) replacing previous import ‘ggplot2::%+%’ by ‘FLCore::%+%’ when loading ‘ggplotFL’
Error: package ‘ggplotFL’ could not be loaded
Execution halted
ERROR: lazy loading failed for package ‘mse’

I've tried to reinstall ggplotFL but I still get the error. I can load the ggplotFL package if I do library(ggplotFL).

Any hints?

**Comment by ldbk** [comment]
I can now install it...

**Comment by iagomosqueira** [comment]
For future reference, this is due to remotes::install_github converting a warning in ggplotFL, from a conflict with ggplot2, into an error. You can call

```
Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS=TRUE)
```

before install_github so the earning does not stop it from installing.
